import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { chmod, lstat, mkdtemp, mkdir, rm, stat, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { after, test } from 'node:test';
import { nextCron } from '../../bin/factory-reporter-scheduler.mjs';

const ROOT = resolve(import.meta.dirname, '..', '..');
const SCHEDULER = join(ROOT, 'bin', 'factory-reporter-scheduler.mjs');
const RUNNER = join(ROOT, 'bin', 'factory-reporter-schedule-runner.mjs');
const roots = [];
const CURRENT_PROFILE = process.platform === 'darwin' ? 'mac' : process.platform === 'win32' ? 'windows-native' : 'wsl';
async function sandbox(profile = 'mac', collection = false, reporting = false) { const root = await mkdtemp(join(tmpdir(), 'factory-reporter-scheduler-test-')); roots.push(root); const config = join(root, 'config.json'); const credential = join(root, 'credential'); await writeFile(credential, 'unit-test-token\n', { mode: 0o600 }); await writeFile(config, JSON.stringify({ schema_version: '1.0', host: { id: 'test-host', profile }, collection: { enabled: collection }, reporting: reporting ? { enabled: true, endpoint: 'http://127.0.0.1:1/api/factory/v1/reports', credential_file: credential } : { enabled: false } })); return { root, config, credential, state: join(root, 'state-home', 'dotagents', 'factory-reporter') }; }
function run(script, args, box) { return new Promise((resolveRun) => { const child = spawn(process.execPath, [script, ...args], { env: { ...process.env, HOME: box.root, USERPROFILE: box.root, LOCALAPPDATA: join(box.root, 'local-app-data'), XDG_CONFIG_HOME: join(box.root, 'config-home'), XDG_STATE_HOME: join(box.root, 'state-home') }, stdio: ['ignore', 'pipe', 'pipe'] }); let stdout = ''; let stderr = ''; child.stdout.on('data', (chunk) => { stdout += chunk; }); child.stderr.on('data', (chunk) => { stderr += chunk; }); child.on('close', (code) => resolveRun({ code, stderr, json: stdout ? JSON.parse(stdout) : null })); }); }
after(async () => { for (const root of roots) await rm(root, { recursive: true, force: true }); });

test('dry-run/apply併用は順序にかかわらず拒否する', async () => { const box = await sandbox(); for (const flags of [['--dry-run', '--apply'], ['--apply', '--dry-run']]) { const result = await run(SCHEDULER, ['install', ...flags, '--config', box.config], box); assert.equal(result.code, 1); assert.match(result.stderr, /併用/); } });
test('配布symlink経由でもscheduler CLIがmainを実行する', async () => { const box = await sandbox('mac'); const link = join(box.root, 'factory-reporter-scheduler'); await symlink(SCHEDULER, link); const result = await run(link, ['install', '--dry-run', '--platform', 'darwin', '--config', box.config], box); assert.equal(result.code, 0, result.stderr); assert.equal(result.json.ok, true); assert.equal(result.json.dry_run, true); });
test('macOS launchdはnode→runnerをXML escapeして生成する', async () => { const box = await sandbox('mac'); const result = await run(SCHEDULER, ['install', '--platform', 'darwin', '--config', box.config], box); assert.equal(result.code, 0); assert.match(result.json.artifact_content, /<string>.*node.*<\/string><string>.*factory-reporter-schedule-runner/); assert.match(result.json.artifact_content, /<key>Minute<\/key><integer>17<\/integer>/); });
test('Linux/WSL cronは厳密single quoteでnode→runnerを起動する', async () => { const box = await sandbox('wsl'); const result = await run(SCHEDULER, ['install', '--platform', 'linux', '--config', box.config], box); assert.equal(result.code, 0); assert.match(result.json.artifact_content, /^17 \* \* \* \* '\/.*node' '\/.*factory-reporter-schedule-runner' --config '/); assert.match(result.json.artifact_content, /# dotagents-factory-reporter\n$/); });
test('Windows Task SchedulerはUTF-8、毎時trigger、private ACL commandをdry-runへ出す', async () => { const box = await sandbox('windows-native'); const result = await run(SCHEDULER, ['install', '--platform', 'win32', '--config', box.config], box); assert.equal(result.code, 0); const xml = result.json.artifact_content; assert.match(xml, /^<\?xml version="1\.0" encoding="UTF-8"\?>/); assert.match(xml, /<Interval>PT1H<\/Interval><Duration>P1D<\/Duration>/); assert.ok(xml.indexOf('<StartBoundary>') < xml.indexOf('<Repetition>')); assert.match(xml, /<Command>.*node.*<\/Command><Arguments>&quot;.*factory-reporter-schedule-runner/); assert.equal(result.json.acl_commands[0][0], 'powershell.exe'); assert.match(result.json.acl_commands[0][6], /SetAccessRuleProtection/); });
test('cron更新はpath変更前のmanaged行だけを置換し、他行と末尾を正規化する', () => { const old = "5 * * * * '/old/node' '/old/runner' --config '/old/config' # dotagents-factory-reporter\nMAILTO=ops\nforeign # dotagents-factory-reporter-extra\n\n"; const updated = nextCron(old, "17 * * * * '/new/node' '/new/runner' --config '/new/config' # dotagents-factory-reporter\n", false); assert.doesNotMatch(updated, /old\/runner/); assert.match(updated, /new\/runner/); assert.match(updated, /MAILTO=ops/); assert.match(updated, /foreign # dotagents-factory-reporter-extra/); const once = nextCron(updated, "17 * * * * '/new/node' '/new/runner' --config '/new/config' # dotagents-factory-reporter\n", true); assert.equal(nextCron(once, "17 * * * * '/new/node' '/new/runner' --config '/new/config' # dotagents-factory-reporter\n", true), once); });
test('cronはsingle quote後もconfig path内のpercentをescapeする', async () => { const box = await sandbox('wsl'); const config = join(box.root, 'config%with%percent.json'); await writeFile(config, JSON.stringify({ schema_version: '1.0', host: { id: 'test-host', profile: 'wsl' }, collection: { enabled: false }, reporting: { enabled: false } })); const result = await run(SCHEDULER, ['install', '--platform', 'linux', '--config', config], box); assert.equal(result.code, 0); assert.match(result.json.artifact_content, /config\\%with\\%percent\.json/); });
test('installはconfigのprofileとtarget不一致・制御文字をfail closedする', async () => { const box = await sandbox('mac'); const mismatch = await run(SCHEDULER, ['install', '--platform', 'linux', '--config', box.config], box); assert.equal(mismatch.code, 1); assert.match(mismatch.stderr, /登録できません/); const newline = await run(SCHEDULER, ['install', '--config', `${box.config}\n`], box); assert.equal(newline.code, 1); assert.match(newline.stderr, /改行/); });
test('collection/reporting=falseのrunnerはstate/outboxを作らず正常skipする', async () => { const box = await sandbox(CURRENT_PROFILE, false); const result = await run(RUNNER, ['--config', box.config], box); assert.equal(result.code, 0); assert.deepEqual(result.json, { ok: true, skipped: 'collection-and-reporting-disabled' }); await assert.rejects(lstat(box.state)); });
test('collection=falseでもreporting=trueなら既存outboxをflushする', async () => { const box = await sandbox(CURRENT_PROFILE, false, true); const result = await run(RUNNER, ['--config', box.config], box); assert.equal(result.code, 0, result.stderr); assert.equal(result.json.command, 'flush'); assert.equal(result.json.reporting_enabled, true); assert.equal(result.json.count, 0); await stat(join(box.state, 'outbox')); await assert.rejects(lstat(join(box.state, 'latest-report.json'))); });
test('runnerはcollection=falseでもhost profileと実platformの不一致をfail closedする', async () => { const box = await sandbox(CURRENT_PROFILE === 'mac' ? 'windows-native' : 'mac', false); const result = await run(RUNNER, ['--config', box.config], box); assert.equal(result.code, 1); assert.match(result.stderr, /実行中platformと一致/); });
test('runnerはprivate lock競合時にscan/enqueue/flushへ進まず非0にする', async () => { const box = await sandbox(CURRENT_PROFILE, true); await mkdir(join(box.state, 'schedule.lock'), { recursive: true }); await writeFile(join(box.state, 'schedule.lock', 'pid'), String(process.pid)); const result = await run(RUNNER, ['--config', box.config], box); assert.equal(result.code, 1); assert.match(result.stderr, /すでに実行中/); });
test('runnerは既存POSIX stateのgroup/other permissionを0700へ矯正する', async () => { const box = await sandbox(CURRENT_PROFILE, true); await mkdir(join(box.state, 'schedule.lock'), { recursive: true }); await chmod(box.state, 0o755); await writeFile(join(box.state, 'schedule.lock', 'pid'), String(process.pid)); const result = await run(RUNNER, ['--config', box.config], box); assert.equal(result.code, 1); assert.equal((await stat(box.state)).mode & 0o777, 0o700); });
