import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { chmod, lstat, mkdtemp, mkdir, readFile, readdir, rm, stat, symlink, writeFile } from 'node:fs/promises';
import { createServer } from 'node:http';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { after, test } from 'node:test';
import { nextCron, removeLegacyArtifacts, stableNodePath } from '../../bin/factory-reporter-scheduler.mjs';

const ROOT = resolve(import.meta.dirname, '..', '..');
const SCHEDULER = join(ROOT, 'bin', 'factory-reporter-scheduler.mjs');
const RUNNER = join(ROOT, 'bin', 'factory-reporter-v2-schedule-runner.mjs');
const roots = [];
const CURRENT_PROFILE = process.platform === 'darwin' ? 'mac' : process.platform === 'win32' ? 'windows-native' : 'wsl';
async function sandbox(profile = 'mac', collection = false, reporting = false) { const root = await mkdtemp(join(tmpdir(), 'factory-reporter-scheduler-test-')); roots.push(root); const config = join(root, 'config.json'); const credential = join(root, 'credential'); await writeFile(credential, 'unit-test-token\n', { mode: 0o600 }); await writeFile(config, JSON.stringify({ schema_version: '1.0', host: { id: 'test-host', profile }, collection: { enabled: collection }, reporting: reporting ? { enabled: true, endpoint: 'http://127.0.0.1:1/api/factory/v2/reports', credential_file: credential } : { enabled: false } })); return { root, config, credential, state: join(root, 'state-home', 'dotagents', 'factory-reporter-v2') }; }
function run(script, args, box, extraEnv = {}) { return new Promise((resolveRun) => { const child = spawn(process.execPath, [script, ...args], { env: { ...process.env, HOME: box.root, USERPROFILE: box.root, LOCALAPPDATA: join(box.root, 'local-app-data'), XDG_CONFIG_HOME: join(box.root, 'config-home'), XDG_STATE_HOME: join(box.root, 'state-home'), ...extraEnv }, stdio: ['ignore', 'pipe', 'pipe'] }); let stdout = ''; let stderr = ''; child.stdout.on('data', (chunk) => { stdout += chunk; }); child.stderr.on('data', (chunk) => { stderr += chunk; }); child.on('close', (code) => { let json = null; for (const line of stdout.trim().split(/\r?\n/u).reverse()) { try { json = JSON.parse(line); break; } catch {} } resolveRun({ code, stderr, json }); }); }); }
async function writeRunnerLock(box, pid, nonce = '00000000-0000-4000-8000-000000000001') { await mkdir(box.state, { recursive: true }); const path = join(box.state, `schedule.lock.${nonce}.owner`); await writeFile(path, `${JSON.stringify({ schema_version: 'dotagents.factory-scheduler-lock.v1', nonce, pid, acquired_at: new Date().toISOString() })}\n`, { mode: 0o600 }); return path; }
after(async () => { for (const root of roots) await rm(root, { recursive: true, force: true }); });

test('macOS Homebrew Nodeはversioned Cellar pathでなくstable入口をschedulerへ保存する', () => {
  assert.equal(stableNodePath('darwin', '/opt/homebrew/Cellar/node/26.5.0/bin/node', (path) => path === '/opt/homebrew/bin/node'), '/opt/homebrew/bin/node');
  assert.equal(stableNodePath('darwin', '/usr/local/Cellar/node/24.1.0/bin/node', (path) => path === '/usr/local/bin/node'), '/usr/local/bin/node');
  assert.throws(() => stableNodePath('darwin', '/opt/homebrew/Cellar/node/26.5.0/bin/node', () => false), /stable Node/);
  assert.equal(stableNodePath('linux', '/home/kite/.nvm/versions/node/v24.14.1/bin/node', () => false), '/home/kite/.nvm/versions/node/v24.14.1/bin/node');
});

test('dry-run/apply併用は順序にかかわらず拒否する', async () => { const box = await sandbox(); for (const flags of [['--dry-run', '--apply'], ['--apply', '--dry-run']]) { const result = await run(SCHEDULER, ['install', ...flags, '--config', box.config], box); assert.equal(result.code, 1); assert.match(result.stderr, /併用/); } });
test('配布symlink経由でもscheduler CLIがmainを実行する', async () => { const box = await sandbox('mac'); const link = join(box.root, 'factory-reporter-scheduler'); await symlink(SCHEDULER, link); const result = await run(link, ['install', '--dry-run', '--platform', 'darwin', '--config', box.config], box); assert.equal(result.code, 0, result.stderr); assert.equal(result.json.ok, true); assert.equal(result.json.dry_run, true); });
test('macOS launchdはnode→v2 runnerをXML escapeして生成する', async () => { const box = await sandbox('mac'); const result = await run(SCHEDULER, ['install', '--platform', 'darwin', '--config', box.config], box); assert.equal(result.code, 0); assert.match(result.json.artifact_content, /<string>.*node.*<\/string><string>.*factory-reporter-v2-schedule-runner/); assert.match(result.json.artifact_content, /<key>Minute<\/key><integer>17<\/integer>/); });
test('Linux/WSL cronは厳密single quoteでnode→v2 runnerを起動する', async () => { const box = await sandbox('wsl'); const result = await run(SCHEDULER, ['install', '--platform', 'linux', '--config', box.config], box); assert.equal(result.code, 0); assert.match(result.json.artifact_content, /^17 \* \* \* \* '\/.*node' '\/.*factory-reporter-v2-schedule-runner' --config '/); assert.match(result.json.artifact_content, /# dotagents-factory-reporter\n$/); });
test('Windows Task SchedulerはUTF-8、毎時trigger、v2 private ACL commandをdry-runへ出す', async () => { const box = await sandbox('windows-native'); const result = await run(SCHEDULER, ['install', '--platform', 'win32', '--config', box.config], box); assert.equal(result.code, 0); const xml = result.json.artifact_content; assert.match(xml, /^<\?xml version="1\.0" encoding="UTF-8"\?>/); assert.match(xml, /<Interval>PT1H<\/Interval><Duration>P1D<\/Duration>/); assert.ok(xml.indexOf('<StartBoundary>') < xml.indexOf('<Repetition>')); assert.match(xml, /<Command>.*node.*<\/Command><Arguments>&quot;.*factory-reporter-v2-schedule-runner/); assert.match(result.json.state, /factory-reporter-v2$/); assert.equal(result.json.acl_commands[0][0], 'powershell.exe'); const acl = result.json.acl_commands[0][6]; assert.match(acl, /DOTAGENTS_FACTORY_ACL_TARGET/); assert.match(acl, /SetAccessRuleProtection\(\$true, \$false\)/); assert.match(acl, /Set-Acl -LiteralPath \$p -AclObject \$acl/); assert.doesNotMatch(acl, /\[IO\.(?:Directory|File)\]::SetAccessControl/); const source = await readFile(SCHEDULER, 'utf8'); assert.match(source, /timeout: 5_000/); assert.match(source, /acl_apply_failed/); });
test('v1指定は各OS artifactをv1 runnerとv1 stateへ切り替え、control artifactをmajor非依存にする', async () => { for (const [platform, profile] of [['darwin', 'mac'], ['linux', 'wsl'], ['win32', 'windows-native']]) { const box = await sandbox(profile); const v1 = await run(SCHEDULER, ['install', '--dry-run', '--platform', platform, '--wire-major', 'v1', '--config', box.config], box); const v2 = await run(SCHEDULER, ['install', '--dry-run', '--platform', platform, '--wire-major', 'v2', '--config', box.config], box); assert.equal(v1.code, 0, v1.stderr); assert.equal(v1.json.wire_major, 'v1'); assert.match(v1.json.artifact_content, /factory-reporter-schedule-runner/); assert.doesNotMatch(v1.json.artifact_content, /factory-reporter-v2-schedule-runner/); assert.match(v1.json.state, /factory-reporter$/); assert.equal(v1.json.artifact, v2.json.artifact); assert.match(v1.json.artifact, /factory-reporter-scheduler/); } });
test('wire-major省略はv2互換のartifactとstateを維持する', async () => { const box = await sandbox('mac'); const result = await run(SCHEDULER, ['install', '--dry-run', '--platform', 'darwin', '--config', box.config], box); assert.equal(result.code, 0); assert.equal(result.json.wire_major, 'v2'); assert.match(result.json.artifact_content, /factory-reporter-v2-schedule-runner/); assert.match(result.json.state, /factory-reporter-v2$/); });
test('reporting ON時はwire-majorとfactory endpoint pathnameの一致を必須にする', async () => { const box = await sandbox('mac', false, true); const v1 = await run(SCHEDULER, ['install', '--dry-run', '--platform', 'darwin', '--wire-major', 'v1', '--config', box.config], box); assert.equal(v1.code, 1); assert.match(v1.stderr, /api\/factory\/v1\/reports/); await writeFile(box.config, JSON.stringify({ schema_version: '1.0', host: { id: 'test-host', profile: 'mac' }, collection: { enabled: false }, reporting: { enabled: true, endpoint: 'http://127.0.0.1:1/api/factory/v1/reports', credential_file: box.credential } })); const v2 = await run(SCHEDULER, ['install', '--dry-run', '--platform', 'darwin', '--wire-major', 'v2', '--config', box.config], box); assert.equal(v2.code, 1); assert.match(v2.stderr, /api\/factory\/v2\/reports/); const accepted = await run(SCHEDULER, ['install', '--dry-run', '--platform', 'darwin', '--wire-major', 'v1', '--config', box.config], box); assert.equal(accepted.code, 0, accepted.stderr); });
test('legacy scheduler artifactだけを掃除し、v1/v2 stateとoutboxを残す', async () => { const box = await sandbox(); const states = [join(box.root, 'state-home', 'dotagents', 'factory-reporter'), join(box.root, 'state-home', 'dotagents', 'factory-reporter-v2')]; for (const state of states) { await mkdir(join(state, 'scheduler'), { recursive: true }); await mkdir(join(state, 'outbox')); await writeFile(join(state, 'scheduler', 'factory-reporter.cron'), 'old artifact'); await writeFile(join(state, 'outbox', 'keep'), 'payload'); } await removeLegacyArtifacts('linux', { legacyStates: states }); for (const state of states) { await assert.rejects(lstat(join(state, 'scheduler', 'factory-reporter.cron'))); await stat(join(state, 'outbox', 'keep')); } });
test('cron更新はpath変更前のmanaged行だけを置換し、他行と末尾を正規化する', () => { const old = "5 * * * * '/old/node' '/old/runner' --config '/old/config' # dotagents-factory-reporter\nMAILTO=ops\nforeign # dotagents-factory-reporter-extra\n\n"; const updated = nextCron(old, "17 * * * * '/new/node' '/new/runner' --config '/new/config' # dotagents-factory-reporter\n", false); assert.doesNotMatch(updated, /old\/runner/); assert.match(updated, /new\/runner/); assert.match(updated, /MAILTO=ops/); assert.match(updated, /foreign # dotagents-factory-reporter-extra/); const once = nextCron(updated, "17 * * * * '/new/node' '/new/runner' --config '/new/config' # dotagents-factory-reporter\n", true); assert.equal(nextCron(once, "17 * * * * '/new/node' '/new/runner' --config '/new/config' # dotagents-factory-reporter\n", true), once); });
test('cronはsingle quote後もconfig path内のpercentをescapeする', async () => { const box = await sandbox('wsl'); const config = join(box.root, 'config%with%percent.json'); await writeFile(config, JSON.stringify({ schema_version: '1.0', host: { id: 'test-host', profile: 'wsl' }, collection: { enabled: false }, reporting: { enabled: false } })); const result = await run(SCHEDULER, ['install', '--platform', 'linux', '--config', config], box); assert.equal(result.code, 0); assert.match(result.json.artifact_content, /config\\%with\\%percent\.json/); });
test('installはconfigのprofileとtarget不一致・制御文字をfail closedする', async () => { const box = await sandbox('mac'); const mismatch = await run(SCHEDULER, ['install', '--platform', 'linux', '--config', box.config], box); assert.equal(mismatch.code, 1); assert.match(mismatch.stderr, /登録できません/); const newline = await run(SCHEDULER, ['install', '--config', `${box.config}\n`], box); assert.equal(newline.code, 1); assert.match(newline.stderr, /改行/); });
test('collection/reporting=falseのrunnerはstate/outboxを作らず正常skipする', async () => { const box = await sandbox(CURRENT_PROFILE, false); const result = await run(RUNNER, ['--config', box.config], box); assert.equal(result.code, 0); assert.deepEqual(result.json, { ok: true, post_gate_status: 'skipped', skipped: 'collection-and-reporting-disabled' }); await assert.rejects(lstat(box.state)); });
test('post-update gateは完全一致allowlist以外のunverifiedと全failをblockingにする', async () => {
  const source = await readFile(RUNNER, 'utf8'); const start = source.indexOf('function gateFailures('); const end = source.indexOf('function hasPendingToolchainLedger', start); const gateFailures = Function(`${source.slice(start, end)}; return gateFailures;`)();
  const required = ['caveat', 'throughline', 'spotter', 'codegraph', 'markitdown', 'gpt-connector', 'aiterm-mcp', 'codex-sidecar', ...(CURRENT_PROFILE === 'server' ? ['servermanager'] : []), ...(CURRENT_PROFILE === 'windows-native' ? [] : ['claude-code', 'codex-cli'])];
  const report = (checks) => ({ products: Object.fromEntries(required.map((id) => [id, { presence_status: 'installed', compatibility_status: 'compatible', checks: checks[id] ?? [] }])) });
  const allowed = { spotter: [{ check_id: 'codex_hooks', status: 'unverified', reason_code: 'trust_not_machine_verifiable' }], throughline: [{ check_id: 'evidence_restore_smoke', status: 'unverified', reason_code: 'diagnostic_unverified' }, { check_id: 'claude_connector', status: 'unverified', reason_code: 'diagnostic_unverified' }], 'aiterm-mcp': [{ check_id: 'pty_list', status: 'unverified', reason_code: 'pty_list_unverified' }] };
  assert.deepEqual(gateFailures(report(allowed), CURRENT_PROFILE, true), []);
  assert.deepEqual(gateFailures(report({ spotter: [{ check_id: 'codex_hooks', status: 'unverified', reason_code: 'different_reason' }] }), CURRENT_PROFILE, true), ['spotter:codex_hooks']);
  assert.deepEqual(gateFailures(report({ throughline: [{ check_id: 'unknown_component', status: 'unverified', reason_code: 'diagnostic_unverified' }] }), CURRENT_PROFILE, true), ['throughline:unknown_component']);
  assert.deepEqual(gateFailures(report({ 'aiterm-mcp': [{ check_id: 'pty_list', status: 'fail', reason_code: 'pty_list_unverified' }] }), CURRENT_PROFILE, true), ['aiterm-mcp:pty_list']);
});
test('collection=falseでもreporting=trueなら既存outboxをflushする', async () => { const box = await sandbox(CURRENT_PROFILE, false, true); const result = await run(RUNNER, ['--config', box.config], box); assert.equal(result.code, 0, result.stderr); assert.deepEqual(result.json, { ok: true, post_gate_status: 'success' }); await stat(join(box.state, 'outbox')); await assert.rejects(lstat(join(box.state, 'latest-report.json'))); });
test('v2 runnerのWindows ACLはreporterと同じLiteralPath・current SID・継承遮断契約を使う', async () => { const source = await readFile(RUNNER, 'utf8'); assert.match(source, /DOTAGENTS_FACTORY_ACL_TARGET/); assert.match(source, /WindowsIdentity\]::GetCurrent\(\)\.User/); assert.match(source, /DirectorySecurity/); assert.match(source, /FileSecurity/); assert.match(source, /SetAccessRuleProtection\(\$true, \$false\)/); assert.match(source, /Set-Acl -LiteralPath \$p -AclObject \$acl/); assert.doesNotMatch(source, /\[IO\.(?:Directory|File)\]::SetAccessControl/); assert.match(source, /timeout: 5_000/); assert.match(source, /acl_apply_failed/); });
test('runnerはcollection=falseでもhost profileと実platformの不一致をfail closedする', async () => { const box = await sandbox(CURRENT_PROFILE === 'mac' ? 'windows-native' : 'mac', false); const result = await run(RUNNER, ['--config', box.config], box); assert.equal(result.code, 1); assert.match(result.stderr, /実行中platformと一致/); });
test('runnerはprivate lock競合時にscan/enqueue/flushへ進まず非0にする', async () => { const box = await sandbox(CURRENT_PROFILE, true); await writeRunnerLock(box, process.pid); const result = await run(RUNNER, ['--config', box.config], box); assert.equal(result.code, 1); assert.match(result.stderr, /すでに実行中/); });
test('runnerは旧directory lockをageだけで奪わず明示回収を要求する', async () => { const box = await sandbox(CURRENT_PROFILE, false, true); const lock = join(box.state, 'schedule.lock'); await mkdir(lock, { recursive: true }); const result = await run(RUNNER, ['--config', box.config], box); assert.equal(result.code, 1); assert.match(result.stderr, /明示回収/); await stat(lock); });
test('runnerは原子的owner contenderの死んだPIDだけを掃除して再実行できる', async () => { const box = await sandbox(CURRENT_PROFILE, false, true); const child = spawn(process.execPath, ['-e', 'process.exit(0)']); const deadPid = child.pid; await new Promise((resolveClose) => child.on('close', resolveClose)); const dead = await writeRunnerLock(box, deadPid); const result = await run(RUNNER, ['--config', box.config], box); assert.equal(result.code, 0, result.stderr); assert.deepEqual(result.json, { ok: true, post_gate_status: 'success' }); await assert.rejects(lstat(dead)); assert.deepEqual((await readdir(box.state)).filter((name) => name.includes('schedule.lock.')), []); });
test('runnerはowner完成後の固有hard-link公開とnonce一致cleanupで共有lock削除を避ける', async () => { const source = await readFile(RUNNER, 'utf8'); assert.match(source, /await link\(temporary, published\)/); assert.match(source, /current\?\.nonce === nonce/); assert.match(source, /schedule\\\.lock\\\.\[0-9a-f-\]\{36\}\\\.owner/); assert.doesNotMatch(source, /\.reclaim|oldEnough|mtimeMs/); });
test('runnerは既存POSIX stateのgroup/other permissionを0700へ矯正する', async () => { const box = await sandbox(CURRENT_PROFILE, true); await chmod(await mkdir(box.state, { recursive: true }).then(() => box.state), 0o755); await writeRunnerLock(box, process.pid); const result = await run(RUNNER, ['--config', box.config], box); assert.equal(result.code, 1); assert.equal((await stat(box.state)).mode & 0o777, 0o700); });
test('v2 runnerはstate symlink先へscan artifactを書かない', async () => { const box = await sandbox(CURRENT_PROFILE, true); const target = join(box.root, 'symlink-target'); await mkdir(target); await mkdir(join(box.root, 'state-home', 'dotagents'), { recursive: true }); await symlink(target, box.state); const result = await run(RUNNER, ['--config', box.config], box); assert.equal(result.code, 1); assert.match(result.stderr, /symlink/); assert.deepEqual(await readdir(target), []); });
test('通常runはcomponent healthをexitへ変換せず、post-updateだけがdefault-deny gateを適用する', async () => { const box = await sandbox(CURRENT_PROFILE, true, false); const bin = join(box.root, 'bin'); await mkdir(bin); for (const name of ['caveat', 'throughline', 'spotter', 'codex-sidecar', 'gpt-connector', 'codegraph', 'markitdown', 'aiterm-mcp', 'claude', 'codex', 'npm', 'grok']) { const file = join(bin, name); await writeFile(file, '#!/bin/sh\nexit 1\n'); await chmod(file, 0o755); } const git = join(bin, 'git'); await writeFile(git, '#!/bin/sh\necho 1234567\n'); await chmod(git, 0o755); const normal = await run(RUNNER, ['--config', box.config], box, { PATH: bin }); assert.equal(normal.code, 0, normal.stderr); const result = await run(RUNNER, ['--config', box.config, '--post-update'], box, { PATH: bin }); assert.equal(result.code, 1); assert.deepEqual(result.json, { ok: false, post_gate_status: 'failed', failed_checks: CURRENT_PROFILE === 'windows-native' ? 8 : 10 }); });
test('finalize-updateは最終ledgerを再投影し、製品failure自体を配送失敗へ偽装しない', async () => { const box = await sandbox(CURRENT_PROFILE, false, false); const bin = join(box.root, 'bin'); await mkdir(bin); for (const name of ['caveat', 'throughline', 'spotter', 'codex-sidecar', 'gpt-connector', 'codegraph', 'markitdown', 'aiterm-mcp', 'claude', 'codex', 'npm', 'grok']) { const file = join(bin, name); await writeFile(file, '#!/bin/sh\nexit 1\n'); await chmod(file, 0o755); } const git = join(bin, 'git'); await writeFile(git, '#!/bin/sh\necho 1234567\n'); await chmod(git, 0o755); const result = await run(RUNNER, ['--config', box.config, '--finalize-update'], box, { PATH: bin }); assert.equal(result.code, 0, result.stderr); assert.deepEqual(result.json, { ok: true, finalized: true }); await stat(join(box.state, 'latest-report.json')); });
test('finalize-updateはpending台帳をenqueue前に拒否しnetworkへ送らない', async () => {
  const requests = [];
  const server = createServer((request, response) => { requests.push(request.url); request.resume(); response.writeHead(200, { 'content-type': 'application/json' }); response.end('{"ok":true}'); });
  await new Promise((resolveListen) => server.listen(0, '127.0.0.1', resolveListen));
  try {
    const box = await sandbox(CURRENT_PROFILE, false, true);
    const address = server.address();
    await writeFile(box.config, JSON.stringify({ schema_version: '1.0', host: { id: 'test-host', profile: CURRENT_PROFILE }, collection: { enabled: false }, reporting: { enabled: true, endpoint: `http://127.0.0.1:${address.port}/api/factory/v2/reports`, credential_file: box.credential } }));
    const bin = join(box.root, 'bin'); await mkdir(bin);
    for (const name of ['caveat', 'throughline', 'spotter', 'codex-sidecar', 'gpt-connector', 'codegraph', 'markitdown', 'aiterm-mcp', 'claude', 'codex', 'npm', 'grok']) { const file = join(bin, name); await writeFile(file, '#!/bin/sh\nexit 1\n'); await chmod(file, 0o755); }
    const git = join(bin, 'git'); await writeFile(git, '#!/bin/sh\necho 1234567\n'); await chmod(git, 0o755);
    const ledgerDirectory = join(box.root, 'state-home', 'agents-update'); await mkdir(ledgerDirectory, { recursive: true });
    const pending = { before_version: null, latest_version: null, operation_status: 'success', after_version: null, post_gate_status: 'pending', reason_code: 'updated', observed_at: '2026-07-13T14:00:00.000Z' };
    await writeFile(join(ledgerDirectory, 'toolchain-ledger.json'), JSON.stringify({ schema_version: 'dotagents.toolchain-update.v1', products: { 'claude-code': pending, 'codex-cli': pending, 'grok-build': pending } }), { mode: 0o600 });
    const result = await run(RUNNER, ['--config', box.config, '--finalize-update'], box, { PATH: bin });
    assert.equal(result.code, 1); assert.match(result.stderr, /post_gate_pending/); assert.deepEqual(requests, []);
  } finally { await new Promise((resolveClose) => server.close(resolveClose)); }
});
